image: Visual Studio 2019

environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 10

cache:
  - .venv -> poetry.lock

init:
  - git config --global core.symlinks true

install:
  # Add Make and Python to the PATH
  - choco install make
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%;%PATH%
  - set PATH=C:\Python%PYTHON_MAJOR%%PYTHON_MINOR%\Scripts;%PATH%
  # Install system dependencies
  - curl -sSL https://install.python-poetry.org | python -
  - set PATH=%USERPROFILE%\AppData\Roaming\Python\Scripts;%PATH%
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test
  - make demo
