language: python
python:
  - 3.8
  - 3.9

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

env:
  global:
    - RANDOM_SEED=0

before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - make doctor

install:
  - make install

script:
  - make check
  - make test
  - make demo

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
