language: python
python:
  - 3.5

cache:
  pip: true
  directories:
    - ~/virtualenv

env:
  global:
    - RANDOM_SEED=0

before_install:
  - make doctor || echo "Some system dependencies might be missing"

install:
  - make install

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: change
