language: python
python:
  - 3.5

cache:
  pip: true
  directories:
    - ~/virtualenv/python3.5.*

env:
  global:
    - RANDOM_SEED=0

before_install:
  - make doctor

install:
  - make install

script:
  - make check
  - make test
  - make demo

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
