site_name: GitMan
site_description: A language-agnostic "dependency manager" using Git.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/gitman

theme: mkdocs

pages:
- Home: index.md
- Setup:
    - Git: setup/git.md
    - Environment: setup/environment.md
- Interfaces:
    - Command Line: interfaces/cli.md
    - Git Plugin: interfaces/plugin.md
    - Package API: interfaces/api.md
- Use Cases:
  - Replacing Submodules: use-cases/submodules.md
  - Tracking Branches: use-cases/branch-tracking.md
  - Linking Feature Branches: use-cases/linked-features.md
  - Build System Integration: use-cases/build-integration.md
  - Sparse Checkouts: use-cases/sparse-checkouts.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
